from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  
    path('Register/', views.Register, name='Register'),
    path('Login/', views.Login, name='Login'),
    path('ReseretPassword/', views.ResetPassword, name='ResetPassword'),
    path('Logout/', views.Logout, name='Logout'),
    path('Profile/', views.Profile, name='Profile'),
    path('Donation/', views.handle_donation, name='Donation'),
    path('DonateFunds/', views.handle_donation, name='DonateFunds'),
    path('Dashboard/', views.Dashboard, name='Dashboard'),
    path('Services/', views.Services, name='Services'),
    path('BloodDonate/', views.BloodDonate, name='BloodDonate'),
    path('BloodRequest/', views.handle_blood_request, name='BloodRequest'),
    path('EditProfile/', views.edit_profile, name='EditProfile'),
    path('HealthScreening/', views.health_screening, name='HealthScreening'),
    path('BloodAlerts/', views.blood_alerts, name='BloodAlerts'),
    path('OrganizeEvent/', views.organize_event, name='OrganizeEvent'),
    path('DonorDashboard/', views.donor_dashboard, name='DonorDashboard'),
    path('donors/edit/<int:donor_id>/', views.admin_edit_donor, name='admin_edit_donor'),
    path('contact/', views.contact, name='contact'),
    path('save-life/', views.save_life, name='save_life'),
    path('health-benefits/', views.health_benefits, name='health_benefits'),
    path('community/', views.community, name='community'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('check-eligibility/', views.check_donation_eligibility, name='check_eligibility'),
    path('not-eligible/', views.not_eligible, name='not_eligible'),
    path('groupdonate/', views.groupdonate, name='groupdonate'),
    path('education/', views.education, name='education'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('doctor/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('appointment/<int:appointment_id>/', views.view_appointment_details, name='view_appointment_details'),
    path('appointment/request/', views.request_appointment, name='request_appointment'),
    path('appointment/<int:appointment_id>/confirm/', views.confirm_appointment, name='confirm_appointment'),
    path('appointment/<int:appointment_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),
    path('appointment/<int:appointment_id>/complete/', views.complete_appointment, name='complete_appointment'),
    path('blood-request/create/', views.create_blood_request, name='create_blood_request'),
    path('blood-request/<int:request_id>/', views.view_blood_request, name='view_blood_request'),
    path('donation/schedule/', views.schedule_donation, name='schedule_donation'),
    path('donation/<int:donation_id>/', views.view_donation_details, name='view_donation_details'),
    path('lab-report/<int:report_id>/', views.view_lab_report, name='view_lab_report'),
]   