# Generated by Django 5.2 on 2025-04-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=20)),
                ('appointment_type', models.CharField(choices=[('In-Person', 'In-Person'), ('Virtual', 'Virtual')], max_length=20)),
                ('selected_doctor', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Contacted', 'Contacted'), ('Scheduled', 'Scheduled'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=20)),
                ('appointment_type', models.CharField(choices=[('In-Person', 'In-Person'), ('Virtual', 'Virtual')], default='In-Person', max_length=20)),
                ('reason_for_visit', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
